// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package datagen

import (
	"database/sql"

	"github.com/google/uuid"
)

type P struct {
	ID   uuid.UUID 
	Name string
	Num  sql.NullString `swaggertype:"number"`
}
