// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package datagen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAllP = `-- name: GetAllP :many
select id, name, num from p
`

func (q *Queries) GetAllP(ctx context.Context) ([]P, error) {
	rows, err := q.db.QueryContext(ctx, getAllP)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []P
	for rows.Next() {
		var i P
		if err := rows.Scan(&i.ID, &i.Name, &i.Num); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneP = `-- name: GetOneP :one
SELECT id, name, num FROM p
WHERE id = $1
`

func (q *Queries) GetOneP(ctx context.Context, id uuid.UUID) (P, error) {
	row := q.db.QueryRowContext(ctx, getOneP, id)
	var i P
	err := row.Scan(&i.ID, &i.Name, &i.Num)
	return i, err
}

const updateOneP = `-- name: UpdateOneP :one
UPDATE p set
    name = COALESCE($1, name),
    num = COALESCE($2, num)
WHERE id = $3
RETURNING id, name, num
`

type UpdateOnePParams struct {
	Name sql.NullString
	Num  sql.NullString
	ID   uuid.UUID
}

func (q *Queries) UpdateOneP(ctx context.Context, arg UpdateOnePParams) (P, error) {
	row := q.db.QueryRowContext(ctx, updateOneP, arg.Name, arg.Num, arg.ID)
	var i P
	err := row.Scan(&i.ID, &i.Name, &i.Num)
	return i, err
}
