services:
  sqlc:
    image: sqlc/sqlc:1.31.1
    volumes:
      - .:/src
    working_dir: /src

  postgres:
    image: postgres:18.3-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 7s
      retries: 4

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes: 
      - ${PROJECT_ROOT}/postgres/migrations:/migrations
      
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports: 
      - "16686:16686"
      - "4317:4317"

volumes:
  postgres_data: